ALTER TABLE products 
ALTER COLUMN name 
DROP NOT NULL;

ALTER TABLE products 
ALTER COLUMN catagory 
DROP NOT NULL;

ALTER TABLE products 
ALTER COLUMN price 
DROP NOT NULL;

ALTER TABLE products 
ALTER COLUMN afteroffer 
DROP NOT NULL;

ALTER TABLE products 
ALTER COLUMN description 
DROP NOT NULL;

ALTER TABLE products 
ALTER COLUMN quantity 
DROP NOT NULL;